### PR TITLE
Proposing blurb in banner

### PR DESCRIPTION
**Pull request by KateMcCall-Kiley**

### CODE REVIEW

**Comment by rossdakin** [comment]
Nice! How about a period at the end?

Here's what it looks like for me:

screen shot 2016-01-08 at 8 01 41 pm

What do you think -- try using a background image?

**Comment by KateMcCall-Kiley** [comment]
Love the idea of an image - how about the one with the flags?
Great call with the period at the end. And can we have 'This site..." start on the next line?

You're awesome.

**Comment by rossdakin** [comment]
Might look nice as multiple paragraphs too:

screen shot 2016-01-08 at 8 03 26 pm

**Comment by KateMcCall-Kiley** [comment]
Oh maybe the flag image with a blue box (of the blue you have there) and the white letter inside it?

**Comment by rossdakin** [comment]
I spoke too soon — good call!

**Comment by KateMcCall-Kiley** [comment]
Totally

**Pull request closed without merging**
